# Generated by Django 3.2.5 on 2021-07-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieDbApp', '0002_streamingplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movieDbApp.streamingplatform'),
            preserve_default=False,
        ),
    ]
