# Generated by Django 3.2.5 on 2021-07-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieDbApp', '0007_auto_20210726_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='numeber_rating',
            new_name='number_rating',
        ),
    ]
