# Generated by Django 3.2.5 on 2021-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieDbApp', '0008_rename_numeber_rating_movie_number_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name ')),
                ('about', models.CharField(max_length=255, verbose_name='About')),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='streamingplatform',
            options={'ordering': ['id'], 'verbose_name': 'StreamingPlatform', 'verbose_name_plural': 'StreamingPlatforms'},
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(related_name='movie_stars', to='movieDbApp.Star'),
        ),
    ]
