# Generated by Django 3.2.5 on 2021-07-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieDbApp', '0010_alter_star_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['id'], 'verbose_name': 'Star', 'verbose_name_plural': 'Stars'},
        ),
    ]
