# Generated by Django 3.2.5 on 2021-08-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieDbApp', '0011_alter_star_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
